language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env: TZ=Europe/Zurich
script:
  - for file in testdata/*.xz; do xz -kde -- "$file"; done
  - |
    err=0
    for test in testdata/*.meta; do
      echo "** test: $test **"

      # no big-endian support
      echo "testing without big-endian support"
      cargo run -- "$test" >"$test.actual" || err=1
      if [ -f "$test.expected-little" ]; then expected="$test.expected-little"; else expected="$test.expected"; fi
      diff -- "$expected" "$test.actual" || err=1

      # big-endian support
      echo "testing with big-endian support"
      cargo run --features "big_endian" -- "$test" >"$test.actual" || err=1
      if [ -f "$test.expected-big" ]; then expected="$test.expected-big"; else expected="$test.expected"; fi
      diff -- "$expected" "$test.actual" || err=1
    done
    [ $err -eq 0 ]
